# Vietnamese NLP Training Configuration

# Data configuration
data:
  data_folder: "./data1"
  tokenizer_file: "checkpoints/vietnamese_tokenizer.json"
  vocab_size: 25000
  max_seq_len: 512
  train_split: 0.8

# Model configuration
model:
  d_model: 768
  n_heads: 12
  n_layers: 12
  d_ff: 3072
  dropout: 0.1

# Training configuration
training:
  batch_size: 16
  learning_rate: 3e-5
  weight_decay: 0.01
  num_epochs: 5
  warmup_steps: 5000
  device: "auto"  # 'cuda', 'cpu', 'mps', or 'auto'

# Generation configuration
generation:
  temperature: 0.8
  top_k: 10
  top_p: 0.9
  max_new_tokens: 256

# Save configuration
save:
  model_save_path: "checkpoints/model/vietnamese_checkpoint.pt"
  config_save_path: "training_config.json"
